CREATE TYPE "streaming_provider" AS ENUM ('BUNNY', 'MUX');
ALTER TABLE "institutions" ADD COLUMN IF NOT EXISTS "course_streaming_provider" "streaming_provider", ADD COLUMN IF NOT EXISTS "course_streaming_credentials" text;
ALTER TABLE "staff" ADD COLUMN IF NOT EXISTS "course_streaming_provider" "streaming_provider", ADD COLUMN IF NOT EXISTS "course_streaming_credentials" text;
CREATE TABLE IF NOT EXISTS "courses" ("id" serial PRIMARY KEY, "institution_id" integer NOT NULL REFERENCES "institutions"("id") ON DELETE CASCADE, "staff_id" integer NOT NULL REFERENCES "staff"("id") ON DELETE CASCADE, "subject_id" integer NOT NULL REFERENCES "subjects"("id") ON DELETE RESTRICT, "title" varchar(180) NOT NULL, "lecture_count" integer NOT NULL CHECK ("lecture_count" > 0 AND "lecture_count" <= 500), "is_active" boolean NOT NULL DEFAULT true, "created_at" timestamp NOT NULL DEFAULT now(), "updated_at" timestamp NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS "courses_institution_staff_idx" ON "courses" ("institution_id", "staff_id");
CREATE TABLE IF NOT EXISTS "course_classes" ("id" serial PRIMARY KEY, "course_id" integer NOT NULL REFERENCES "courses"("id") ON DELETE CASCADE, "class_id" integer NOT NULL REFERENCES "classes"("id") ON DELETE CASCADE, CONSTRAINT "course_classes_course_class_unique" UNIQUE ("course_id", "class_id"));
CREATE TABLE IF NOT EXISTS "course_lectures" ("id" serial PRIMARY KEY, "course_id" integer NOT NULL REFERENCES "courses"("id") ON DELETE CASCADE, "sequence" integer NOT NULL CHECK ("sequence" > 0), "title" varchar(180) NOT NULL, "description" text, "video_url" varchar(1000) NOT NULL, "created_at" timestamp NOT NULL DEFAULT now(), "updated_at" timestamp NOT NULL DEFAULT now(), CONSTRAINT "course_lectures_course_sequence_unique" UNIQUE ("course_id", "sequence"));
CREATE TABLE IF NOT EXISTS "course_lecture_progress" ("id" serial PRIMARY KEY, "lecture_id" integer NOT NULL REFERENCES "course_lectures"("id") ON DELETE CASCADE, "student_id" integer NOT NULL REFERENCES "students"("id") ON DELETE CASCADE, "read_at" timestamp NOT NULL DEFAULT now(), CONSTRAINT "course_lecture_progress_lecture_student_unique" UNIQUE ("lecture_id", "student_id"));
CREATE INDEX IF NOT EXISTS "course_lecture_progress_student_idx" ON "course_lecture_progress" ("student_id");
