'use client';
import type { PageDesign } from '@/lib/public-site-builder';
const field = 'mt-1 w-full rounded-lg border border-stone-200 bg-white p-2.5 text-sm';
export function PageDesignControls({ value, onChange, website = false, compact = false, fallbackAccent = '#233c32' }: { value: PageDesign; onChange: (value: PageDesign) => void; website?: boolean; compact?: boolean; fallbackAccent?: string }) {
  return <div className={compact ? 'grid gap-4' : 'grid gap-4 sm:grid-cols-2'}>
    <label className="block text-sm font-medium">Brand color<div className="mt-1 flex items-center gap-2"><input type="color" aria-label="Brand color" value={value.accent || fallbackAccent} onChange={(e) => onChange({ ...value, accent: e.target.value })} className="h-11 w-14 cursor-pointer rounded border" /><span className="text-xs">{value.accent || 'Theme default'}</span><button type="button" className="ml-auto text-xs underline" onClick={() => { const next = { ...value }; delete next.accent; onChange(next); }}>Reset</button></div></label>
    <label className="block text-sm font-medium">Typography<select aria-label="Typography" className={field} value={value.font || 'default'} onChange={(e) => onChange({ ...value, font: e.target.value as PageDesign['font'] })}><option value="default">Theme default</option><option value="sans">Clean sans serif</option><option value="serif">Classic serif</option></select></label>
    <label className="block text-sm font-medium">Page background<select aria-label="Page background" className={field} value={value.background || 'warm'} onChange={(e) => onChange({ ...value, background: e.target.value as PageDesign['background'] })}><option value="warm">Warm paper</option><option value="white">Pure white</option></select></label>
    <label className="block text-sm font-medium">Content width<select aria-label="Content width" className={field} value={value.width || 'standard'} onChange={(e) => onChange({ ...value, width: e.target.value as PageDesign['width'] })}><option value="standard">Focused</option><option value="wide">Wide</option></select></label>
    <label className="block text-sm font-medium">Section spacing<select aria-label="Section spacing" className={field} value={value.spacing || 'relaxed'} onChange={(e) => onChange({ ...value, spacing: e.target.value as PageDesign['spacing'] })}><option value="relaxed">Spacious</option><option value="compact">Compact</option></select></label>
    <label className="block text-sm font-medium">Hero layout<select aria-label="Hero layout" className={field} value={value.hero || (website ? '' : 'split')} onChange={(e) => { const next = { ...value }; if (e.target.value) next.hero = e.target.value as PageDesign['hero']; else delete next.hero; onChange(next); }}>{website && <option value="">Theme default</option>}<option value="split">Text beside image</option><option value="banner">Image above headline</option><option value="minimal">Headline only</option></select></label>
  </div>;
}
